name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Validate manifest.json
      run: |
        if ! jq . manifest.json >/dev/null 2>&1; then
          echo "manifest.json is not valid JSON"
          exit 1
        fi
    
    - name: Check file structure
      run: |
        for file in popup.html popup.js content.js manifest.json; do
          if [ ! -f "$file" ]; then
            echo "Missing required file: $file"
            exit 1
          fi
        done
        
        if [ ! -d "icons" ]; then
          echo "Missing icons directory"
          exit 1
        fi
    
    - name: Validate icon files
      run: |
        for size in 16 48 128; do
          if [ ! -f "icons/icon${size}.png" ]; then
            echo "Missing icon${size}.png"
            exit 1
          fi
        done 